#!/usr/bin/env python3
import argparse
import pathlib
import re
import sys
from typing import Optional


DISABLED_SCRIPTS = (
    "../common/js/jssdk.js",
    "../common/js/watermark.js",
    "../common/js/server.js",
    "../common/js/getUserInfo.js",
)

PREVIEW_BOOTSTRAP = """<script>
    window.__ARES_STATIC_PREVIEW__ = true;

    window.addEventListener('pageshow', function(e) {
        if (e.persisted) { location.reload(); }
    });

    window.wx = window.wx || {
        ready: function(fn) {
            if (typeof fn === 'function') {
                fn();
            }
        },
        hideAllNonBaseMenuItem: function() {},
        invoke: function() {},
        chooseImage: function() {},
        uploadImage: function() {},
        startRecord: function() {},
        stopRecord: function() {},
        closeWindow: function() {}
    };

    window.initJSSDK = window.initJSSDK || function() {};
    window.__canvasWM = window.__canvasWM || function() {};
    window.$http = window.$http || function() {
        return Promise.resolve({ retcode: 'success', data: [] });
    };
    window.$Upload = window.$Upload || function() {
        return Promise.resolve({ retcode: 'success', data: {} });
    };

    if (window.$ && typeof $.cookie === 'function') {
        (function(originalCookie) {
            $.cookie = function(name) {
                if (arguments.length === 1 && name === 'user') {
                    return JSON.stringify({ name: '静态预览' });
                }
                return originalCookie.apply(this, arguments);
            };
        })($.cookie);
    }

    $(function() {
        if (typeof initFun === 'function') {
            initFun();
        }
    });
</script>"""


def disable_runtime_script_tags(content: str) -> str:
    for src in DISABLED_SCRIPTS:
        pattern = re.compile(
            r'[ \t]*<script[^>]*src="' + re.escape(src) + r'"[^>]*></script>\s*\n?',
            re.IGNORECASE,
        )
        replacement = '    <!-- static preview disabled: {0} -->\n'.format(src)
        content = pattern.sub(replacement, content)
    return content


def replace_runtime_inline_block(content: str) -> str:
    inline_pattern = re.compile(
        r"<script>\s*.*?function getUserFinish\(\)\s*\{.*?\}\s*</script>\s*",
        re.DOTALL,
    )

    if inline_pattern.search(content):
        return inline_pattern.sub(PREVIEW_BOOTSTRAP + "\n", content, count=1)

    body_close = "</body>"
    if body_close in content:
        return content.replace(body_close, PREVIEW_BOOTSTRAP + "\n" + body_close, 1)
    return content + "\n" + PREVIEW_BOOTSTRAP + "\n"


def build_output_path(html_path: pathlib.Path, output_path: Optional[str]) -> pathlib.Path:
    if output_path:
        return pathlib.Path(output_path).expanduser().resolve()
    return html_path.with_name(html_path.stem + ".preview.html")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a static-preview companion HTML for an ARES page."
    )
    parser.add_argument("html_path", help="Source ARES HTML file")
    parser.add_argument(
        "--output",
        help="Optional output path; defaults to <source>.preview.html",
    )
    args = parser.parse_args()

    html_path = pathlib.Path(args.html_path).expanduser().resolve()
    if not html_path.exists():
        print("Source file not found: {0}".format(html_path), file=sys.stderr)
        return 1

    content = html_path.read_text(encoding="utf-8")
    content = disable_runtime_script_tags(content)
    content = replace_runtime_inline_block(content)

    marker = "<!-- Generated by ares-static-preview -->\n"
    if not content.startswith(marker):
        content = marker + content

    output_path = build_output_path(html_path, args.output)
    output_path.write_text(content, encoding="utf-8")
    print(str(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
