#!/usr/bin/env python3
import argparse
import os
import pathlib
import re
import sys
from typing import Optional


DISABLED_SCRIPTS = (
    "../common/js/jssdk.js",
    "../common/js/watermark.js",
    "../common/js/server.js",
    "../common/js/getUserInfo.js",
)


def script_tag(src: str) -> str:
    return '    <script type="text/javascript" src="{0}"></script>'.format(src)


def runtime_inline_block(jssdk_perms: str) -> str:
    perms = [item.strip() for item in jssdk_perms.split(",") if item.strip()]
    quoted = ", ".join(["'{0}'".format(item) for item in perms])
    template = """<script>
    // var vConsole = new VConsole();

    window.addEventListener('pageshow', function(e) {
        if (e.persisted) { location.reload(); }
    });

    $(function() {
        initJSSDK([__JSSDK_PERMS__]);
        wx.ready(function() {
            wx.hideAllNonBaseMenuItem();
        });
    });

    function getUserFinish() {
        var username = $.parseJSON($.cookie('user')).name;
        __canvasWM({ content: username });
        initFun();
    }
</script>"""
    return template.replace("__JSSDK_PERMS__", quoted)


def compute_output_path(source_path: pathlib.Path, output: Optional[str]) -> pathlib.Path:
    if output:
        return pathlib.Path(output).expanduser().resolve()

    name = source_path.name
    if name.endswith(".preview.html"):
        return source_path.with_name(name.replace(".preview.html", ".runtime.html"))
    return source_path.with_name(source_path.stem + ".runtime.html")


def compute_common_rel(output_path: pathlib.Path) -> str:
    parts = output_path.resolve().parts
    if "ares" not in parts:
        return "../common"

    ares_index = len(parts) - 1 - parts[::-1].index("ares")
    common_path = pathlib.Path(*parts[: ares_index + 1]) / "common"
    return os.path.relpath(str(common_path), str(output_path.parent)).replace(os.sep, "/")


def extract_title(content: str, fallback: str) -> str:
    match = re.search(r"<title>(.*?)</title>", content, re.IGNORECASE | re.DOTALL)
    if match:
        return match.group(1).strip() or fallback
    return fallback


def extract_body_inner(content: str) -> str:
    match = re.search(r"<body[^>]*>(.*)</body>", content, re.IGNORECASE | re.DOTALL)
    if match:
        return match.group(1).strip()
    return content.strip()


def strip_script_blocks(content: str) -> str:
    return re.sub(r"<script\b[^>]*>.*?</script>", "", content, flags=re.IGNORECASE | re.DOTALL)


def reenable_preview_content(content: str, jssdk_perms: str) -> str:
    content = re.sub(r"<!-- Generated by ares-static-preview -->\s*\n?", "", content)

    for src in DISABLED_SCRIPTS:
        comment = r"[ \t]*<!-- static preview disabled: " + re.escape(src) + r" -->"
        content = re.sub(comment, script_tag(src), content)

    preview_block = re.compile(
        r"<script>\s*window\.__ARES_STATIC_PREVIEW__\s*=\s*true;.*?</script>\s*",
        re.IGNORECASE | re.DOTALL,
    )
    content = preview_block.sub(runtime_inline_block(jssdk_perms) + "\n", content, count=1)
    return content


def wrap_static_content(
    content: str,
    output_path: pathlib.Path,
    title: str,
    css_path: str,
    js_path: str,
    jssdk_perms: str,
) -> str:
    common_rel = compute_common_rel(output_path)
    body_inner = strip_script_blocks(extract_body_inner(content)).strip()

    if re.search(r'<div[^>]+id=["\']app["\']', body_inner, re.IGNORECASE):
        app_block = body_inner
    else:
        app_block = '    <div id="app" v-cloak>\n{0}\n    </div>'.format(body_inner or "        <!-- 页面内容 -->")

    return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover"
          name="viewport" />
    <title>{0}</title>
    <link rel="stylesheet" href="{1}/css/weui.min.css" />
    <link rel="stylesheet" href="{1}/css/jquery-weui.min.css" />
    <link rel="stylesheet" href="{1}/css/vant-2.12.css" />
    <link rel="stylesheet" href="{2}" />
</head>
<body>
{3}
</body>

<script type="text/javascript" src="{1}/js/vue.min.js"></script>
<script type="text/javascript" src="{1}/js/vant-2.12.min.js"></script>
<script type="text/javascript" src="{1}/js/jquery-2.1.3.min.js"></script>
<script type="text/javascript" src="{1}/js/jquery-weui.min.js"></script>
<script type="text/javascript" src="{1}/js/jquery.cookie_jq.js"></script>
<script type="text/javascript" src="{1}/js/base.js"></script>
<script type="text/javascript" src="{1}/js/jssdk.js"></script>
<script type="text/javascript" src="{1}/js/watermark.js"></script>
<script type="text/javascript" src="{1}/js/server.js"></script>
<script type="text/javascript" src="{4}?v=1.0.0"></script>
<!-- <script type="text/javascript" src="{1}/js/vConsole.min.js"></script> -->
{5}
<script type="text/javascript" src="{1}/js/getUserInfo.js"></script>
</html>
""".format(title, common_rel, css_path, app_block, js_path, runtime_inline_block(jssdk_perms))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Restore an ARES runtime-ready page from a static or preview HTML."
    )
    parser.add_argument("source_html", help="Source static or preview HTML")
    parser.add_argument("--output", help="Output HTML path")
    parser.add_argument("--title", help="Page title when wrapping a generic static page")
    parser.add_argument("--css", help="Private CSS path to include in restored page")
    parser.add_argument("--js", help="Private JS path to include in restored page")
    parser.add_argument(
        "--jssdk-perms",
        default="hideAllNonBaseMenuItem,invoke,chooseImage,uploadImage",
        help="Comma-separated JSSDK permissions for runtime block",
    )
    args = parser.parse_args()

    source_path = pathlib.Path(args.source_html).expanduser().resolve()
    if not source_path.exists():
        print("Source file not found: {0}".format(source_path), file=sys.stderr)
        return 1

    output_path = compute_output_path(source_path, args.output)
    content = source_path.read_text(encoding="utf-8")

    if "__ARES_STATIC_PREVIEW__" in content or "static preview disabled:" in content:
        restored = reenable_preview_content(content, args.jssdk_perms)
    else:
        title = args.title or extract_title(content, output_path.stem)
        css_path = args.css or "css/{0}.css".format(output_path.stem.replace(".runtime", ""))
        js_path = args.js or "js/{0}.js".format(output_path.stem.replace(".runtime", ""))
        restored = wrap_static_content(content, output_path, title, css_path, js_path, args.jssdk_perms)

    output_path.write_text(restored, encoding="utf-8")
    print(str(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
